Repository pytest-dev/pytest-html, pull requests merged in 2020-10, with the labels that each got.

#344 Enable devel pipeline
  .github/workflows/tox.yml
  tox.ini
Labels: skip-changelog, test

#346 Avoid duplicate builds on github
  .github/workflows/tox.yml
Labels: skip-changelog, test

#347 Stop shadowing the 'format' builtin
  pytest_html/extras.py
  pytest_html/plugin.py
Labels: bug, major

#345 Add support for py39
  .github/workflows/tox.yml
  setup.cfg
  setup.py
  tox.ini
Labels: enhancement

#348 Add flake8-builtins plugin to the flake8 precommit hook
  .pre-commit-config.yaml
Labels: enhancement, skip-changelog

#349 Support tox isolated builds
  pyproject.toml
  tox.ini
Labels: enhancement, skip-changelog

#351 Add Github Actions workflow for nodejs portion of project
  .github/workflows/actions.yml
Labels: Infrastructure, skip-changelog

#354 Use os.makedirs(exist_ok=True).
  pytest_html/plugin.py
Labels: skip-changelog

#353 Respect pytest --capture=no and -s flags
  CHANGES.rst
  pytest_html/plugin.py
  testing/test_pytest_html.py
Labels: bug

#357 Enable testing on Windows and MacOS
  .github/workflows/actions.yml
  testing/test_pytest_html.py
Labels: skip-changelog, test

#362 Prep version 3.0.0 for release
  CHANGES.rst
Labels: release

#359 Respect --show-capture=no flag
  CHANGES.rst
  pytest_html/plugin.py
  testing/test_pytest_html.py
Labels: bug
