Repository pytest-dev/pytest-html, pull requests merged in 2020-11, with the labels that each got.

#360 Move release from travis to github actions
  .github/workflows/actions.yml
  .travis.yml
  README.rst
  development.rst
  tox.ini
Labels: Infrastructure, packaging, test

#364 Assure scm versioning is pypa compatible
  pyproject.toml
  setup.py
Labels: bug, packaging

#366 Remove appveyor.yml
  appveyor.yml
Labels: Infrastructure, skip-changelog

#365 Add a package.json file for a better javascript development experience
  .github/workflows/actions.yml
  development.rst
  package.json
Labels: Infrastructure, skip-changelog

#361 Add release-drafter config
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: skip-changelog

#368 Update the gitignore file
  .gitignore
Labels: Infrastructure, skip-changelog

#367 Add ESLint to project
  .eslintrc.json
  .pre-commit-config.yaml
  pytest_html/resources/main.js
Labels: test

#371 Remove outdated release instruction
  development.rst
Labels: docs, skip-changelog

#370 Add codecov support for python code
  .coveragerc
  .github/workflows/actions.yml
  .gitignore
  tox.ini
Labels: skip-changelog, test

#379 Add codecov badge to readme
  README.rst
Labels: docs, skip-changelog

#380 Allow for report duration formatting
  CHANGES.rst
  README.rst
  pytest_html/plugin.py
  pytest_html/resources/main.js
  testing/js_test_report.html
  testing/test.js
  testing/test_pytest_html.py
Labels: enhancement, feature

#382 Disable codecov PR comments
  .coveragerc
  codecov.yml
Labels: Infrastructure, skip-changelog

#384 move module to src directory
  .pre-commit-config.yaml
  setup.py
  src/pytest_html/__init__.py
  src/pytest_html/extras.py
  src/pytest_html/hooks.py
  src/pytest_html/plugin.py
  src/pytest_html/resources/main.js
  src/pytest_html/resources/style.css
  testing/js_test_report.html
Labels: enhancement
