Repository pytest-dev/pytest-html, pull requests merged in 2020-12, with the labels that each got.

#387 Stop attaching test reruns to final test report entries
  CHANGES.rst
  src/pytest_html/plugin.py
  testing/test_pytest_html.py
Labels: bug

#398 Fix readme typos
  README.rst
Labels: docs, skip-changelog

#394 Prep version 3.1.0 for release
  CHANGES.rst
Labels: docs, skip-changelog

#396 Remove pkg_resources
  pyproject.toml
  src/.gitignore
  src/pytest_html/__init__.py
  src/pytest_html/plugin.py
Labels: enhancement

#402 Move documentation to read the docs
  .github/workflows/actions.yml
  .gitignore
  docs/Makefile
  docs/conf.py
  docs/development.rst
  docs/index.rst
  docs/installing.rst
  docs/make.bat
  docs/user_guide.rst
  tox.ini
Labels: docs, enhancement

#390 Setup reporting for missing CSS file
  CHANGES.rst
  src/pytest_html/plugin.py
  testing/test_pytest_html.py
Labels: bug

#400 Document how to modify the environment section after tests are finished
  docs/user_guide.rst
Labels: docs, skip-changelog

#405 Cleanup README file
  README.rst
  development.rst
Labels: docs, skip-changelog

#393 Use scss nesting & variables
  src/layout/css/style.scss
  src/pytest_html/resources/style.css
Labels: code quality

#410 Enable eslint camelcase rule
  .eslintrc.json
  src/pytest_html/plugin.py
  src/pytest_html/resources/main.js
  testing/test.js
Labels: code quality

#411 Set release date for v3.1.1
  CHANGES.rst
Labels: docs, skip-changelog

#420 Make the report tab title reflect the report name
  CHANGES.rst
  src/pytest_html/plugin.py
  testing/test_pytest_html.py
Labels: feature

#416 Bump Black and Flake8 deps
  .pre-commit-config.yaml
  Pipfile
  testing/test_pytest_html.py
Labels: Infrastructure, skip-changelog

#414 Handle flaky windows test by rerunning
  Pipfile
  testing/test_pytest_html.py
Labels: skip-changelog, test

#415 Add plugin hooks to RTD documentation
  docs/api_reference.rst
  docs/conf.py
  docs/index.rst
Labels: docs, skip-changelog

#424 remove phantomjs dependency
  package.json
Labels: packaging, skip-changelog

#425 properly classify all npm dependencies
  package.json
Labels: packaging, skip-changelog

#423 Move the changelog to read the docs
  .pre-commit-config.yaml
  README.rst
  docs/changelog.rst
  docs/development.rst
  docs/index.rst
Labels: docs, skip-changelog

#427 split plugin.py into smaller files
  src/pytest_html/html_report.py
  src/pytest_html/outcome.py
  src/pytest_html/plugin.py
  src/pytest_html/result.py
  src/pytest_html/util.py
  testing/test_pytest_html.py
Labels: code quality, skip-changelog

#433 Implement the visible URL query parameter to control visibility of test results on page load.
  docs/changelog.rst
  docs/user_guide.rst
  src/pytest_html/resources/main.js
Labels: feature
