Repository pytest-dev/pytest-html, pull requests merged in 2024-11, with the labels that each got.

#435 Add mypy to CI pipeline and begin typing modules
  .pre-commit-config.yaml
  pyproject.toml
  src/pytest_html/__init__.py
  src/pytest_html/extras.py
  testing/legacy_test_pytest_html.py
Labels: skip-changelog, Infrastructure, code quality

#846 [pre-commit] Add pyproject-fmt to normalize the pyproject.toml
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip-changelog, code quality, dependencies

#847 Fix the pyproject.toml following concurrent merge
  pyproject.toml
Labels: skip-changelog, code quality

#848 Upgrade tool for python 3.9
  .pre-commit-config.yaml
  src/pytest_html/basereport.py
  src/pytest_html/extras.py
  testing/legacy_test_pytest_html.py
Labels: skip-changelog, code quality, dependencies
